name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Запуск раз в сутки в полночь UTC
  workflow_dispatch: # Позволяет запускать вручную через кнопку

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: master
          upstream_sync_repo: ggml-org/whisper.cpp
